"use client";

import { BookOpen, Check, Languages, Volume2 } from "lucide-react";
import { useAuth } from "@/lib/auth-provider";
import { useI18n } from "@/lib/i18n";
import { Button, Card } from "@/components/ui";

export default function LandingPage() {
  const { user, loading, signInWithGoogle, error } = useAuth(); const { t } = useI18n();
  if (loading || user) return <div className="grid min-h-screen place-items-center bg-background text-sm text-muted-foreground">{t("loading")}</div>;
  return <main className="min-h-screen overflow-hidden bg-background"><div className="mx-auto grid min-h-screen max-w-6xl items-center gap-12 px-5 py-10 lg:grid-cols-[1fr_1fr] lg:px-10"><section className="relative"><div className="mb-10 flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary text-primary-foreground"><BookOpen className="h-5 w-5" /></span><span className="text-lg font-bold">{t("appName")}</span></div><p className="mb-4 text-sm font-semibold uppercase tracking-[.22em] text-primary">{t("tagline")}</p><h1 className="max-w-xl text-4xl font-bold tracking-tight sm:text-6xl">{t("welcome")}</h1><p className="mt-5 max-w-md text-base leading-7 text-muted-foreground">{t("signInSubtitle")}</p><Card className="mt-8 max-w-md p-5"><Button className="w-full" size="lg" onClick={() => { void signInWithGoogle(); }}><GoogleIcon />{t("google")}</Button>{error && <p className="mt-3 rounded-xl bg-destructive/10 px-3 py-2 text-sm text-destructive">{t("authError")} {error}</p>}<p className="mt-4 text-center text-xs text-muted-foreground">Google OAuth uses Nhost PKCE and keeps credentials out of the browser.</p></Card></section><section className="relative mx-auto w-full max-w-md"><div className="absolute -inset-12 rounded-full bg-primary/10 blur-3xl" /><div className="relative rotate-[-4deg] rounded-[2rem] border border-border/80 bg-card p-5 shadow-2xl"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>Daily review</span><span className="rounded-full bg-success/15 px-2 py-1 text-success">+24 XP</span></div><div className="mt-5 rounded-[1.5rem] border border-primary/30 bg-background p-8 text-center"><p className="text-xs uppercase tracking-[.2em] text-muted-foreground">English</p><p className="mt-6 text-4xl font-bold">reliable</p><div className="mx-auto mt-8 flex w-fit items-center gap-2 rounded-full bg-accent px-3 py-2 text-xs"><Volume2 className="h-4 w-4 text-primary" />Listen and remember</div></div><div className="mt-5 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-xl bg-muted p-3"><Languages className="mx-auto mb-1 h-4 w-4 text-primary" />2 languages</div><div className="rounded-xl bg-muted p-3"><Check className="mx-auto mb-1 h-4 w-4 text-success" />Focused</div><div className="rounded-xl bg-muted p-3"><BookOpen className="mx-auto mb-1 h-4 w-4 text-primary" />Your sets</div></div></div></section></div></main>;
}

function GoogleIcon() { return <span className="grid h-5 w-5 place-items-center rounded-full bg-white text-sm font-bold text-[#4285F4]">G</span>; }
