"use client";

import { BookOpen, Check, Target, TrendingUp } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Card, ProgressBar } from "@/components/ui";
import { listSets } from "@/lib/nhost/graphql";
import { getSetStats, type VocabularySet } from "@/lib/types";
import { useI18n } from "@/lib/i18n";

export default function ProgressPage() { const { t } = useI18n(); const [sets, setSets] = useState<VocabularySet[]>([]); useEffect(() => { void listSets().then(setSets); }, []); const stats = useMemo(() => sets.reduce((acc, set) => { const next = getSetStats(set); return { total: acc.total + next.total, learned: acc.learned + next.learned, learning: acc.learning + next.learning }; }, { total: 0, learned: 0, learning: 0 }), [sets]); const percent = stats.total ? Math.round(stats.learned / stats.total * 100) : 0; return <AppShell title={t("progress")}><div className="grid gap-3 sm:grid-cols-3"><Kpi icon={<BookOpen />} label={t("totalWords")} value={stats.total} /><Kpi icon={<Check />} label={t("learnedWords")} value={stats.learned} tone="success" /><Kpi icon={<Target />} label={t("activeSets")} value={sets.length} /></div><Card className="mt-5 p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Overall progress</p><p className="mt-1 text-3xl font-bold">{percent}%</p></div><TrendingUp className="h-8 w-8 text-primary" /></div><div className="mt-5"><ProgressBar value={percent} /></div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>{stats.learned} {t("learned")}</span><span>{stats.learning} {t("learning")}</span></div></Card><div className="mt-5 space-y-3">{sets.map((set) => { const value = getSetStats(set); return <Card key={set.id} className="p-4"><div className="flex justify-between gap-3"><p className="font-semibold">{set.title}</p><p className="text-sm font-bold text-primary">{value.progress}%</p></div><div className="mt-3"><ProgressBar value={value.progress} /></div></Card>; })}</div>{sets.length === 0 && <p className="mt-8 text-center text-sm text-muted-foreground">{t("noProgress")}</p>}</AppShell>; }
function Kpi({ icon, label, value, tone = "primary" }: { icon: React.ReactNode; label: string; value: number; tone?: "primary" | "success" }) { return <Card className="p-4"><div className={`mb-3 grid h-9 w-9 place-items-center rounded-xl ${tone === "success" ? "bg-success/15 text-success" : "bg-primary/15 text-primary"}`}>{icon}</div><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></Card>; }
