"use client";

import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { AnswerState, TestSummary } from "@/components/test-summary";
import { Button, Card, Input, ProgressBar } from "@/components/ui";
import { getSet, updateCard } from "@/lib/nhost/graphql";
import type { VocabularyCard } from "@/lib/types";
import { useI18n } from "@/lib/i18n";

export default function WrittenTestPage() { const { setId } = useParams<{ setId: string }>(); const { t } = useI18n(); const [cards, setCards] = useState<VocabularyCard[]>([]); const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(""); const [correct, setCorrect] = useState(0); const [submitted, setSubmitted] = useState(false); useEffect(() => { void getSet(setId).then((set) => setCards(set?.cards ?? [])); }, [setId]); const current = cards[index]; const submit = async () => { if (!current || submitted) return; const isCorrect = answer.trim().toLocaleLowerCase() === current.term.trim().toLocaleLowerCase(); setSubmitted(true); if (isCorrect) setCorrect((value) => value + 1); await updateCard(current.id, { [isCorrect ? "correct_answers" : "incorrect_answers"]: current[isCorrect ? "correct_answers" : "incorrect_answers"] + 1 }); }; const next = () => { setIndex((value) => value + 1); setAnswer(""); setSubmitted(false); }; const restart = () => { setIndex(0); setAnswer(""); setSubmitted(false); setCorrect(0); }; if (cards.length === 0) return <AppShell title={t("written")} back={`/sets/${setId}`}><p className="text-sm text-muted-foreground">{t("loading")}</p></AppShell>; if (index >= cards.length) return <AppShell title={t("test")} back={`/sets/${setId}`} hideNav><TestSummary setId={setId} correct={correct} total={cards.length} onAgain={restart} /></AppShell>; return <AppShell title={t("written")} back={`/sets/${setId}`}><div className="mx-auto max-w-2xl"><div className="mb-4 flex justify-between text-xs text-muted-foreground"><span>{index + 1} / {cards.length}</span><span>{correct} {t("correctAnswers")}</span></div><ProgressBar value={(index / cards.length) * 100} /><Card className="mt-7 p-7 text-center sm:p-12"><p className="text-xs uppercase tracking-[.2em] text-muted-foreground">{t("writePrompt")}</p><h2 className="mt-6 text-3xl font-bold">{current.translation}</h2></Card><div className="mt-5 flex gap-2"><Input value={answer} onChange={(event) => setAnswer(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void submit(); }} disabled={submitted} autoFocus placeholder={t("englishTerm")} /><Button onClick={() => submitted ? next() : void submit()} disabled={!answer.trim()}>{submitted ? t("next") : t("check")}</Button></div>{submitted && <div className="mt-4"><AnswerState correct={answer.trim().toLocaleLowerCase() === current.term.trim().toLocaleLowerCase()} answer={current.term} /></div>}</div></AppShell>; }
